### PR TITLE
Add changes

### PR DESCRIPTION
**Pull request by apandey09**

### CODE REVIEW

**Comment by tehstun** [comment]
"demon" and "no" both need to be removed from the package.json, they are unneeded to be put into the build.

**Comment by apandey09** [comment]
Alright, I think I understand what I'm asked to do here. But before I get to that, I just want to make sure if this is the correct procedure for me to accomplish the latest task you've assigned me.

- Open the command prompt and go to the legacy folder
- run npm install
- run npm uninstall (or is it npm uninstall nodemon?)

Again, I think this is the correct procedure, but I want to run this by you first before proceeding.

**Comment by tehstun** [comment]
no need to run npm install, just run npm uninstall per package :) feel free to do some googles before waiting for my reply, there is a lot of information on this topic.

**Comment by apandey09** [comment]
Got it, thanks! However, I took another look at the package.json file and saw that "nodemon" was on there twice. Should I remove one of those as well, or should I just leave them alone?

**Comment by tehstun** [comment]
well done, ill spin it up tomorrow morning and have a look at it :) should be good to merge from there.

**Comment by tehstun** [comment]
no problem, we can then move on to taking the new designs into this site

**Comment by apandey09** [comment]
Nice! Let me know what's next in terms of projects.

**Pull request merged**
