### PR TITLE
Update team.html

### PR DESCRIPTION
**Pull request by apandey09**
Committed and (I think) pulled the changes onto the right branch this time, As always, let me know if there's anything wrong or missing. Thanks!

### CODE REVIEW

**Comment by tehstun** [comment]
Have you tested that its working correctly?

**Comment by apandey09** [comment]
@tehstun No, I have not because I'm not clear on how to got about testing your changes before committing them. This would be good to know now since I actually would like to go back and change a few lines to the team.html file on my branch.

**Comment by tehstun** [comment]
@apandey09 from within the legacy folder within a command prompt, type

* npm install
* npm install nodemon
* npm run dev
* then navigate to localhost:3000

you will then be able to make changes, and refresh to see changes :)

**Comment by apandey09** [comment]
@tehstun Thanks for the info, man! I really appreciate it.

**Comment by tehstun** [comment]
@apandey09 Sorry but you also need to udpate "about.html" to match the changes made on team.html :) You will see why when you test it

**Comment by apandey09** [comment]
@tehstun Thanks for letting me know! Much appreciated.

**Pull request merged**
